---

# MELT REVIEW

---

100 empleados de una empresa tech con evaluaciones de habilidades. Tiene 14 columnas organizadas en tres grupos semánticos, y eso es la clave del diseño para practicar `melt()`.

Columnas identificadoras (candidatas a `id_vars`): <span style='color:royalblue'>**employee_id, name, department, seniority**</span>

`Grupo 1` — Skills técnicos y blandos (7 columnas): <span style='color:crimson'>**python, sql, excel, tableau, communication, leadership, problem_solving**</span> — scores del 1 al 10

`Grupo 2` — Métricas generales (3 columnas): <span style='color:crimson'>**years_experience, projects_completed, satisfaction**</span>

Lo que hace este dataset útil para `melt()` es que te obliga a practicar cada parámetro:

- `id_vars` → ['employee_id', 'name', 'department', 'seniority'] — las columnas que permanecen fijas
- `value_vars` → Aquí está lo interesante: si no lo especificas, Pandas meltea todas las columnas no listadas en id_vars (*skills + métricas mezcladas, lo cual no tiene sentido semántico*). Para hacer un melt limpio, necesitas seleccionar solo las 7 skills
- `var_name` → El default `'variable'` no dice nada. Necesitas renombrarlo a <span style='color:orange'>**'skill'**</span>
- `value_name` → El default `'value'` tampoco. Necesitas <span style='color:orange'>**'score'`**</span>
- `ignore_index` → Prueba con True vs False para ver cómo cambia el index del resultado

<br>

>---
>
>**La diferencia clave con el dataset (wide_to_long) es que aquí las columnas no tienen un patrón stub+sufijo (revenue_Q1, revenue_Q2...) — son nombres independientes (python, sql, excel...). Esa es exactamente la distinción entre cuándo usar `melt()` y cuándo usar `wide_to_long()`.**
>
>---

<br>

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Use the "on_bad_lines='warn'" or "on_bad_lines='skip'" to keep working. Otherwise will raise an error
# ----------------------------------------------------------------------
#df_error = pd.read_csv('Resources/books.csv', on_bad_lines='warn')
#df_error

In [3]:
df = pd.read_csv('employee_skills.csv', )
df.head()

,employee_id,name,department,seniority,python,sql,excel,tableau,communication,leadership,problem_solving,years_experience,projects_completed,satisfaction
0,EMP-001,Emilio Gutiérrez,Sales,Junior,1.7,1.8,7.4,4.6,6.9,4.7,4.5,3,6,7.3
1,EMP-002,Lucía Martínez,Product,Mid,3.8,5.6,4.8,5.4,7.0,6.7,7.6,3,13,6.6
2,EMP-003,Daniel Ramírez,HR,Junior,1.8,2.8,3.6,2.0,6.0,4.7,6.2,3,10,2.9
3,EMP-004,Alejandro Vargas,Sales,Junior,1.5,3.3,4.8,4.0,6.2,4.8,5.8,2,11,9.0
4,EMP-005,Sara Reyes,HR,Mid,1.4,2.8,6.5,5.1,8.0,7.5,6.3,4,14,6.3

In [4]:
# Working only with "id_vars"
(df.melt(id_vars=['employee_id', 'name',])
   .sort_values(by=['employee_id', 'variable'], 
                ignore_index=True))

     employee_id              name          variable   value
0        EMP-001  Emilio Gutiérrez     communication     6.9
1        EMP-001  Emilio Gutiérrez        department   Sales
2        EMP-001  Emilio Gutiérrez             excel     7.4
3        EMP-001  Emilio Gutiérrez        leadership     4.7
4        EMP-001  Emilio Gutiérrez   problem_solving     4.5
...          ...               ...               ...     ...
1195     EMP-100  Fernanda Ramírez      satisfaction     6.1
1196     EMP-100  Fernanda Ramírez         seniority  Junior
1197     EMP-100  Fernanda Ramírez               sql     2.1
1198     EMP-100  Fernanda Ramírez           tableau     2.0
1199     EMP-100  Fernanda Ramírez  years_experience       3

[1200 rows x 4 columns]

In [5]:
# Working only with "id_vars"
(df.melt(id_vars=['employee_id', 'name', 'department', 'seniority'])
   .sort_values(by='employee_id', ignore_index=True))

,employee_id,name,department,seniority,variable,value
0,EMP-001,Emilio Gutiérrez,Sales,Junior,python,1.7
1,EMP-001,Emilio Gutiérrez,Sales,Junior,projects_completed,6.0
2,EMP-001,Emilio Gutiérrez,Sales,Junior,years_experience,3.0
3,EMP-001,Emilio Gutiérrez,Sales,Junior,problem_solving,4.5
4,EMP-001,Emilio Gutiérrez,Sales,Junior,leadership,4.7
...,...,...,...,...,...,...
995,EMP-100,Fernanda Ramírez,HR,Junior,excel,6.2
996,EMP-100,Fernanda Ramírez,HR,Junior,sql,2.1
997,EMP-100,Fernanda Ramírez,HR,Junior,python,2.0
998,EMP-100,Fernanda Ramírez,HR,Junior,projects_completed,9.0
999,EMP-100,Fernanda Ramírez,HR,Junior,satisfaction,6.1

<br>

---

## Skills por grupo
<br>

In [23]:
df1 = (df
    .melt(id_vars=['employee_id', 'name', 'department', 'seniority'],
          value_vars=['python', 'sql', 'excel', 'tableau', 'communication', 
                      'leadership', 'problem_solving'],
          var_name='skill', 
          value_name='score',
          ignore_index=False)
    .sort_values(by=['employee_id', 'skill'])
)

df1.head(20)

  employee_id              name department seniority            skill  score
0     EMP-001  Emilio Gutiérrez      Sales    Junior    communication    6.9
0     EMP-001  Emilio Gutiérrez      Sales    Junior            excel    7.4
0     EMP-001  Emilio Gutiérrez      Sales    Junior       leadership    4.7
0     EMP-001  Emilio Gutiérrez      Sales    Junior  problem_solving    4.5
0     EMP-001  Emilio Gutiérrez      Sales    Junior           python    1.7
0     EMP-001  Emilio Gutiérrez      Sales    Junior              sql    1.8
0     EMP-001  Emilio Gutiérrez      Sales    Junior          tableau    4.6
1     EMP-002    Lucía Martínez    Product       Mid    communication    7.0
1     EMP-002    Lucía Martínez    Product       Mid            excel    4.8
1     EMP-002    Lucía Martínez    Product       Mid       leadership    6.7
1     EMP-002    Lucía Martínez    Product       Mid  problem_solving    7.6
1     EMP-002    Lucía Martínez    Product       Mid           python    3.8
1     EMP-002    Lucía Martínez    Product       Mid              sql    5.6
1     EMP-002    Lucía Martínez    Product       Mid          tableau    5.4
2     EMP-003    Daniel Ramírez         HR    Junior    communication    6.0
2     EMP-003    Daniel Ramírez         HR    Junior            excel    3.6
2     EMP-003    Daniel Ramírez         HR    Junior       leadership    4.7
2     EMP-003    Daniel Ramírez         HR    Junior  problem_solving    6.2
2     EMP-003    Daniel Ramírez         HR    Junior           python    1.8
2     EMP-003    Daniel Ramírez         HR    Junior              sql    2.8

In [26]:
df1 = (df
    .melt(id_vars=['employee_id', 'name', 'department', 'seniority'],
          value_vars=['python', 'sql', 'excel', 'tableau', 'communication', 
                      'leadership', 'problem_solving'],
          var_name='skill', 
          value_name='score', #ignore_index=True
         )
    .sort_values(by=['employee_id', 'skill'], ignore_index=True)
)

df1.head(20)

   employee_id              name department seniority            skill  score
0      EMP-001  Emilio Gutiérrez      Sales    Junior    communication    6.9
1      EMP-001  Emilio Gutiérrez      Sales    Junior            excel    7.4
2      EMP-001  Emilio Gutiérrez      Sales    Junior       leadership    4.7
3      EMP-001  Emilio Gutiérrez      Sales    Junior  problem_solving    4.5
4      EMP-001  Emilio Gutiérrez      Sales    Junior           python    1.7
5      EMP-001  Emilio Gutiérrez      Sales    Junior              sql    1.8
6      EMP-001  Emilio Gutiérrez      Sales    Junior          tableau    4.6
7      EMP-002    Lucía Martínez    Product       Mid    communication    7.0
8      EMP-002    Lucía Martínez    Product       Mid            excel    4.8
9      EMP-002    Lucía Martínez    Product       Mid       leadership    6.7
10     EMP-002    Lucía Martínez    Product       Mid  problem_solving    7.6
11     EMP-002    Lucía Martínez    Product       Mid           python    3.8
12     EMP-002    Lucía Martínez    Product       Mid              sql    5.6
13     EMP-002    Lucía Martínez    Product       Mid          tableau    5.4
14     EMP-003    Daniel Ramírez         HR    Junior    communication    6.0
15     EMP-003    Daniel Ramírez         HR    Junior            excel    3.6
16     EMP-003    Daniel Ramírez         HR    Junior       leadership    4.7
17     EMP-003    Daniel Ramírez         HR    Junior  problem_solving    6.2
18     EMP-003    Daniel Ramírez         HR    Junior           python    1.8
19     EMP-003    Daniel Ramírez         HR    Junior              sql    2.8

<br>

---

## Soft Skills por Grupo
<br>

In [28]:
df2 = (df
    .melt(id_vars=['employee_id', 'name', 'department', 'seniority'],
          value_vars=['years_experience', 'projects_completed', 'satisfaction'],
          var_name='Seniority',
          value_name='score', 
          ignore_index=False)
    .sort_values(by=['employee_id', 'Seniority'])
)
df2.head(7)

,employee_id,name,department,seniority,Seniority,score
0,EMP-001,Emilio Gutiérrez,Sales,Junior,projects_completed,6.0
0,EMP-001,Emilio Gutiérrez,Sales,Junior,satisfaction,7.3
0,EMP-001,Emilio Gutiérrez,Sales,Junior,years_experience,3.0
1,EMP-002,Lucía Martínez,Product,Mid,projects_completed,13.0
1,EMP-002,Lucía Martínez,Product,Mid,satisfaction,6.6
1,EMP-002,Lucía Martínez,Product,Mid,years_experience,3.0
2,EMP-003,Daniel Ramírez,HR,Junior,projects_completed,10.0

In [29]:
df2 = (df
    .melt(id_vars=['employee_id', 'name', 'department', 'seniority'],
          value_vars=['years_experience', 'projects_completed', 'satisfaction'],
          var_name='Seniority',
          value_name='score', #ignore_index=True
         )
    .sort_values(by=['employee_id', 'Seniority'], ignore_index=True)
)
df2.head(7)

,employee_id,name,department,seniority,Seniority,score
0,EMP-001,Emilio Gutiérrez,Sales,Junior,projects_completed,6.0
1,EMP-001,Emilio Gutiérrez,Sales,Junior,satisfaction,7.3
2,EMP-001,Emilio Gutiérrez,Sales,Junior,years_experience,3.0
3,EMP-002,Lucía Martínez,Product,Mid,projects_completed,13.0
4,EMP-002,Lucía Martínez,Product,Mid,satisfaction,6.6
5,EMP-002,Lucía Martínez,Product,Mid,years_experience,3.0
6,EMP-003,Daniel Ramírez,HR,Junior,projects_completed,10.0