---

# REVIEW OF WIDE TO LONG 

---

<br>

100 tiendas ficticias de retail en ciudades de Latinoamérica, con 16 columnas. El dataset está diseñado intencionalmente para que necesites cada parámetro de `wide_to_long()`:

Estructura de las columnas wide:
<span style='color:crimson'>**revenue_Q1, revenue_Q2, customers_Q1, customers_Q2, returns_Q3, returns_Q4...**

Esto te obliga a usar:

- `stubnames` → <span style='color:royalblue'>**'revenue', 'customers', 'returns'**</span> — tres métricas distintas que unpivotear
- `i` → <span style='color:royalblue'>**store_id**</span> — la Primary Key que identifica unívocamente cada tienda
- `j` → <span style='color:royalblue'>**quarter**</span> — el nombre que le das a la nueva columna con los sufijos Q1–Q4
- `sep` → <span style='color:royalblue'>**'_'**</span> — el separador entre el stub y el sufijo (sin esto, Pandas buscaría columnas llamadas revenueQ1 sin guión bajo)
- `suffix` → <span style='color:royalblue'>**r'\w+'**</span> — aquí está la trampa pedagógica: por default, suffix es <span style='color:crimson'>**r'\d+'**</span> (solo dígitos). Pero tus sufijos son Q1, Q2, etc., que empiezan con letra. Si no cambias `suffix`, `wide_to_long()` no va a encontrar ninguna columna que matchee y te devuelve un DataFrame vacío sin error aparente

Ese último punto es especialmente importante — es un bug silencioso que genera mucha confusión cuando uno está aprendiendo esta función.

<br>

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('latam_retail_stores.csv')
df

,store_id,city,country,category,revenue_Q1,customers_Q1,returns_Q1,revenue_Q2,customers_Q2,returns_Q2,revenue_Q3,customers_Q3,returns_Q3,revenue_Q4,customers_Q4,returns_Q4
0,ST-001,Buenos Aires,Argentina,Hogar,101452.93,897,42,94527.78,1622,83,118162.69,900,106,156112.91,1320,62
1,ST-002,La Paz,Bolivia,Hogar,61716.59,2267,50,72636.76,2299,88,83847.61,1947,89,98582.58,2183,123
2,ST-003,Mendoza,Argentina,Ropa,109457.89,1923,9,123080.65,2470,11,108691.24,1754,24,124286.73,3375,17
3,ST-004,Cusco,Perú,Ropa,74565.98,1787,44,87198.70,1280,33,57984.74,1445,40,81341.77,2442,49
4,ST-005,Medellín,Colombia,Electrónica,46825.32,261,55,36988.82,313,112,47815.79,291,50,52198.00,243,152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ST-096,Cochabamba,Bolivia,Electrónica,100821.27,1537,107,131652.59,1894,73,124785.24,1800,125,136808.69,2109,146
96,ST-097,Bogotá,Colombia,Deportes,73081.43,2048,114,91054.70,2598,82,73095.99,2821,148,99992.20,2445,118
97,ST-098,Caracas,Venezuela,Hogar,43853.41,334,84,52751.77,261,38,59727.46,348,72,63736.39,386,95
98,ST-099,Cochabamba,Bolivia,Alimentos,64604.53,1713,53,72751.64,2116,134,69000.02,2098,147,84460.59,2318,160
99,ST-100,Mendoza,Argentina,Electrónica,33230.51,1681,18,34666.25,2736,23,39083.45,2588,13,43448.62,3532,30

<br>

---

# Práctica No. 1
<br>

In [3]:
df1 = (pd.wide_to_long(df=df,
                 stubnames=['customers', 'returns', 'revenue'],
                 i=['store_id'],
                 j='quarter',
                 sep='_',
                 suffix=r'\w\d')
)

df1.head(10)

,,category,city,country,customers,returns,revenue
store_id,quarter,,,,,,
ST-001,Q1,Hogar,Buenos Aires,Argentina,897,42,101452.93
ST-002,Q1,Hogar,La Paz,Bolivia,2267,50,61716.59
ST-003,Q1,Ropa,Mendoza,Argentina,1923,9,109457.89
ST-004,Q1,Ropa,Cusco,Perú,1787,44,74565.98
ST-005,Q1,Electrónica,Medellín,Colombia,261,55,46825.32
ST-006,Q1,Hogar,Córdoba,Argentina,678,63,39325.96
ST-007,Q1,Ropa,Quito,Ecuador,1410,60,17396.19
ST-008,Q1,Deportes,Santiago,Chile,1996,37,43889.03
ST-009,Q1,Alimentos,Buenos Aires,Argentina,1252,64,46467.71
ST-010,Q1,Hogar,Cochabamba,Bolivia,1310,111,15537.61

In [4]:
df1 = (pd
    .wide_to_long(df=df,
                  stubnames=['customers', 'returns', 'revenue'],
                  i=['store_id'],
                  j='quarter',
                  sep='_',
                  suffix=r'\w\d')
    .sort_values(by='store_id')
)

df1.head(10)

                 category          city    country  customers  returns  \
store_id quarter
ST-001   Q1         Hogar  Buenos Aires  Argentina        897       42
         Q3         Hogar  Buenos Aires  Argentina        900      106
         Q4         Hogar  Buenos Aires  Argentina       1320       62
         Q2         Hogar  Buenos Aires  Argentina       1622       83
ST-002   Q1         Hogar        La Paz    Bolivia       2267       50
         Q3         Hogar        La Paz    Bolivia       1947       89
         Q2         Hogar        La Paz    Bolivia       2299       88
         Q4         Hogar        La Paz    Bolivia       2183      123
ST-003   Q4          Ropa       Mendoza  Argentina       3375       17
         Q3          Ropa       Mendoza  Argentina       1754       24

                    revenue
store_id quarter
ST-001   Q1       101452.93
         Q3       118162.69
         Q4       156112.91
         Q2        94527.78
ST-002   Q1        61716.59
         Q3        83847.61
         Q2        72636.76
         Q4        98582.58
ST-003   Q4       124286.73
         Q3       108691.24

<br>

---

# Práctica No. 2

<br>

In [5]:
df2 = (pd.wide_to_long(df=df,
                       stubnames=['customers', 'returns', 'revenue'],
                       i=['store_id', 'category', 'country','city'],
                       j='quarter',
                       sep='_',
                       suffix=r'\w\d')
)

df2.head(10)

                                                  customers  returns  \
store_id category country   city         quarter
ST-001   Hogar    Argentina Buenos Aires Q1             897       42
                                         Q2            1622       83
                                         Q3             900      106
                                         Q4            1320       62
ST-002   Hogar    Bolivia   La Paz       Q1            2267       50
                                         Q2            2299       88
                                         Q3            1947       89
                                         Q4            2183      123
ST-003   Ropa     Argentina Mendoza      Q1            1923        9
                                         Q2            2470       11

                                                    revenue
store_id category country   city         quarter
ST-001   Hogar    Argentina Buenos Aires Q1       101452.93
                                         Q2        94527.78
                                         Q3       118162.69
                                         Q4       156112.91
ST-002   Hogar    Bolivia   La Paz       Q1        61716.59
                                         Q2        72636.76
                                         Q3        83847.61
                                         Q4        98582.58
ST-003   Ropa     Argentina Mendoza      Q1       109457.89
                                         Q2       123080.65

In [6]:
# DataFrame Original
df.head(3)

,store_id,city,country,category,revenue_Q1,customers_Q1,returns_Q1,revenue_Q2,customers_Q2,returns_Q2,revenue_Q3,customers_Q3,returns_Q3,revenue_Q4,customers_Q4,returns_Q4
0,ST-001,Buenos Aires,Argentina,Hogar,101452.93,897,42,94527.78,1622,83,118162.69,900,106,156112.91,1320,62
1,ST-002,La Paz,Bolivia,Hogar,61716.59,2267,50,72636.76,2299,88,83847.61,1947,89,98582.58,2183,123
2,ST-003,Mendoza,Argentina,Ropa,109457.89,1923,9,123080.65,2470,11,108691.24,1754,24,124286.73,3375,17